### PR TITLE
Add an event to pass screenshots / 添加一个事件来传递屏幕截图

### PR DESCRIPTION
**Pull request by SwaggyMacro**
Remove the way that saves screenshots through the clipboard. Add an event to pass the bitmap of the screenshot.

### CODE REVIEW

**Comment by SwaggyMacro** [comment]
这个UI库看起来非常棒，但是使用过程中发现ScreenCut类没有提供截图结束后传递截图的事件，只能够通过Clipboard获取截图，有一点不填方便。😊

**Comment by Kellyskill** [comment]
Shows my $ in my wallet balance…

**Comment by Kellyskill** [comment]
Good feedback z

**Review by Kellyskill — COMMENTED** [review]
Unsuspended my blockchain wallet balance $ to shows my account balance...

**Comment by Kellyskill** [comment]
Good feedback boss...

**Comment by Kellyskill** [comment]
The same email with this one .. i am using to message you ..

**Comment by Kellyskill** [comment]
imageimageimageimageimage





Resolved my access wallet problem.. to Unsuspended and shows my $ in my blockchain wallet balance too ..

**Comment by SwaggyMacro** [comment]
> 谢谢喜欢我们的库，也非常感谢 @SwaggyMacro 大佬的贡献

没又没有，不敢当，您才是大佬🤗

**Pull request merged**
